# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: application.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61pplication.proto\x12\x06PB_App\"*\n\x0cStartRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x01(\t\"\x13\n\x11LockStatusRequest\"$\n\x12LockStatusResponse\x12\x0e\n\x06locked\x18\x01 \x01(\x08\"\x10\n\x0e\x41ppExitRequest\"\"\n\x12\x41ppLoadFileRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"4\n\x15\x41ppButtonPressRequest\x12\x0c\n\x04\x61rgs\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\x05\"\x19\n\x17\x41ppButtonReleaseRequest\";\n\x1c\x41ppButtonPressReleaseRequest\x12\x0c\n\x04\x61rgs\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\x05\"3\n\x10\x41ppStateResponse\x12\x1f\n\x05state\x18\x01 \x01(\x0e\x32\x10.PB_App.AppState\"\x11\n\x0fGetErrorRequest\".\n\x10GetErrorResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0c\n\x04text\x18\x02 \x01(\t\"#\n\x13\x44\x61taExchangeRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c*+\n\x08\x41ppState\x12\x0e\n\nAPP_CLOSED\x10\x00\x12\x0f\n\x0b\x41PP_STARTED\x10\x01\x42!\n\x1f\x63om.flipperdevices.protobuf.appb\x06proto3')

_APPSTATE = DESCRIPTOR.enum_types_by_name['AppState']
AppState = enum_type_wrapper.EnumTypeWrapper(_APPSTATE)
APP_CLOSED = 0
APP_STARTED = 1


_STARTREQUEST = DESCRIPTOR.message_types_by_name['StartRequest']
_LOCKSTATUSREQUEST = DESCRIPTOR.message_types_by_name['LockStatusRequest']
_LOCKSTATUSRESPONSE = DESCRIPTOR.message_types_by_name['LockStatusResponse']
_APPEXITREQUEST = DESCRIPTOR.message_types_by_name['AppExitRequest']
_APPLOADFILEREQUEST = DESCRIPTOR.message_types_by_name['AppLoadFileRequest']
_APPBUTTONPRESSREQUEST = DESCRIPTOR.message_types_by_name['AppButtonPressRequest']
_APPBUTTONRELEASEREQUEST = DESCRIPTOR.message_types_by_name['AppButtonReleaseRequest']
_APPBUTTONPRESSRELEASEREQUEST = DESCRIPTOR.message_types_by_name['AppButtonPressReleaseRequest']
_APPSTATERESPONSE = DESCRIPTOR.message_types_by_name['AppStateResponse']
_GETERRORREQUEST = DESCRIPTOR.message_types_by_name['GetErrorRequest']
_GETERRORRESPONSE = DESCRIPTOR.message_types_by_name['GetErrorResponse']
_DATAEXCHANGEREQUEST = DESCRIPTOR.message_types_by_name['DataExchangeRequest']
StartRequest = _reflection.GeneratedProtocolMessageType('StartRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTREQUEST,
  '__module__' : 'application_pb2'
  # @@protoc_insertion_point(class_scope:PB_App.StartRequest)
  })
_sym_db.RegisterMessage(StartRequest)

LockStatusRequest = _reflection.GeneratedProtocolMessageType('LockStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOCKSTATUSREQUEST,
  '__module__' : 'application_pb2'
  # @@protoc_insertion_point(class_scope:PB_App.LockStatusRequest)
  })
_sym_db.RegisterMessage(LockStatusRequest)

LockStatusResponse = _reflection.GeneratedProtocolMessageType('LockStatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOCKSTATUSRESPONSE,
  '__module__' : 'application_pb2'
  # @@protoc_insertion_point(class_scope:PB_App.LockStatusResponse)
  })
_sym_db.RegisterMessage(LockStatusResponse)

AppExitRequest = _reflection.GeneratedProtocolMessageType('AppExitRequest', (_message.Message,), {
  'DESCRIPTOR' : _APPEXITREQUEST,
  '__module__' : 'application_pb2'
  # @@protoc_insertion_point(class_scope:PB_App.AppExitRequest)
  })
_sym_db.RegisterMessage(AppExitRequest)

AppLoadFileRequest = _reflection.GeneratedProtocolMessageType('AppLoadFileRequest', (_message.Message,), {
  'DESCRIPTOR' : _APPLOADFILEREQUEST,
  '__module__' : 'application_pb2'
  # @@protoc_insertion_point(class_scope:PB_App.AppLoadFileRequest)
  })
_sym_db.RegisterMessage(AppLoadFileRequest)

AppButtonPressRequest = _reflection.GeneratedProtocolMessageType('AppButtonPressRequest', (_message.Message,), {
  'DESCRIPTOR' : _APPBUTTONPRESSREQUEST,
  '__module__' : 'application_pb2'
  # @@protoc_insertion_point(class_scope:PB_App.AppButtonPressRequest)
  })
_sym_db.RegisterMessage(AppButtonPressRequest)

AppButtonReleaseRequest = _reflection.GeneratedProtocolMessageType('AppButtonReleaseRequest', (_message.Message,), {
  'DESCRIPTOR' : _APPBUTTONRELEASEREQUEST,
  '__module__' : 'application_pb2'
  # @@protoc_insertion_point(class_scope:PB_App.AppButtonReleaseRequest)
  })
_sym_db.RegisterMessage(AppButtonReleaseRequest)

AppButtonPressReleaseRequest = _reflection.GeneratedProtocolMessageType('AppButtonPressReleaseRequest', (_message.Message,), {
  'DESCRIPTOR' : _APPBUTTONPRESSRELEASEREQUEST,
  '__module__' : 'application_pb2'
  # @@protoc_insertion_point(class_scope:PB_App.AppButtonPressReleaseRequest)
  })
_sym_db.RegisterMessage(AppButtonPressReleaseRequest)

AppStateResponse = _reflection.GeneratedProtocolMessageType('AppStateResponse', (_message.Message,), {
  'DESCRIPTOR' : _APPSTATERESPONSE,
  '__module__' : 'application_pb2'
  # @@protoc_insertion_point(class_scope:PB_App.AppStateResponse)
  })
_sym_db.RegisterMessage(AppStateResponse)

GetErrorRequest = _reflection.GeneratedProtocolMessageType('GetErrorRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETERRORREQUEST,
  '__module__' : 'application_pb2'
  # @@protoc_insertion_point(class_scope:PB_App.GetErrorRequest)
  })
_sym_db.RegisterMessage(GetErrorRequest)

GetErrorResponse = _reflection.GeneratedProtocolMessageType('GetErrorResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETERRORRESPONSE,
  '__module__' : 'application_pb2'
  # @@protoc_insertion_point(class_scope:PB_App.GetErrorResponse)
  })
_sym_db.RegisterMessage(GetErrorResponse)

DataExchangeRequest = _reflection.GeneratedProtocolMessageType('DataExchangeRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATAEXCHANGEREQUEST,
  '__module__' : 'application_pb2'
  # @@protoc_insertion_point(class_scope:PB_App.DataExchangeRequest)
  })
_sym_db.RegisterMessage(DataExchangeRequest)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037com.flipperdevices.protobuf.app'
  _APPSTATE._serialized_start=485
  _APPSTATE._serialized_end=528
  _STARTREQUEST._serialized_start=29
  _STARTREQUEST._serialized_end=71
  _LOCKSTATUSREQUEST._serialized_start=73
  _LOCKSTATUSREQUEST._serialized_end=92
  _LOCKSTATUSRESPONSE._serialized_start=94
  _LOCKSTATUSRESPONSE._serialized_end=130
  _APPEXITREQUEST._serialized_start=132
  _APPEXITREQUEST._serialized_end=148
  _APPLOADFILEREQUEST._serialized_start=150
  _APPLOADFILEREQUEST._serialized_end=184
  _APPBUTTONPRESSREQUEST._serialized_start=186
  _APPBUTTONPRESSREQUEST._serialized_end=238
  _APPBUTTONRELEASEREQUEST._serialized_start=240
  _APPBUTTONRELEASEREQUEST._serialized_end=265
  _APPBUTTONPRESSRELEASEREQUEST._serialized_start=267
  _APPBUTTONPRESSRELEASEREQUEST._serialized_end=326
  _APPSTATERESPONSE._serialized_start=328
  _APPSTATERESPONSE._serialized_end=379
  _GETERRORREQUEST._serialized_start=381
  _GETERRORREQUEST._serialized_end=398
  _GETERRORRESPONSE._serialized_start=400
  _GETERRORRESPONSE._serialized_end=446
  _DATAEXCHANGEREQUEST._serialized_start=448
  _DATAEXCHANGEREQUEST._serialized_end=483
# @@protoc_insertion_point(module_scope)
