# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: desktop.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdesktop.proto\x12\nPB_Desktop\"\x11\n\x0fIsLockedRequest\"\x0f\n\rUnlockRequest\"\x18\n\x16StatusSubscribeRequest\"\x1a\n\x18StatusUnsubscribeRequest\"\x18\n\x06Status\x12\x0e\n\x06locked\x18\x01 \x01(\x08\x42%\n#com.flipperdevices.protobuf.desktopb\x06proto3')



_ISLOCKEDREQUEST = DESCRIPTOR.message_types_by_name['IsLockedRequest']
_UNLOCKREQUEST = DESCRIPTOR.message_types_by_name['UnlockRequest']
_STATUSSUBSCRIBEREQUEST = DESCRIPTOR.message_types_by_name['StatusSubscribeRequest']
_STATUSUNSUBSCRIBEREQUEST = DESCRIPTOR.message_types_by_name['StatusUnsubscribeRequest']
_STATUS = DESCRIPTOR.message_types_by_name['Status']
IsLockedRequest = _reflection.GeneratedProtocolMessageType('IsLockedRequest', (_message.Message,), {
  'DESCRIPTOR' : _ISLOCKEDREQUEST,
  '__module__' : 'desktop_pb2'
  # @@protoc_insertion_point(class_scope:PB_Desktop.IsLockedRequest)
  })
_sym_db.RegisterMessage(IsLockedRequest)

UnlockRequest = _reflection.GeneratedProtocolMessageType('UnlockRequest', (_message.Message,), {
  'DESCRIPTOR' : _UNLOCKREQUEST,
  '__module__' : 'desktop_pb2'
  # @@protoc_insertion_point(class_scope:PB_Desktop.UnlockRequest)
  })
_sym_db.RegisterMessage(UnlockRequest)

StatusSubscribeRequest = _reflection.GeneratedProtocolMessageType('StatusSubscribeRequest', (_message.Message,), {
  'DESCRIPTOR' : _STATUSSUBSCRIBEREQUEST,
  '__module__' : 'desktop_pb2'
  # @@protoc_insertion_point(class_scope:PB_Desktop.StatusSubscribeRequest)
  })
_sym_db.RegisterMessage(StatusSubscribeRequest)

StatusUnsubscribeRequest = _reflection.GeneratedProtocolMessageType('StatusUnsubscribeRequest', (_message.Message,), {
  'DESCRIPTOR' : _STATUSUNSUBSCRIBEREQUEST,
  '__module__' : 'desktop_pb2'
  # @@protoc_insertion_point(class_scope:PB_Desktop.StatusUnsubscribeRequest)
  })
_sym_db.RegisterMessage(StatusUnsubscribeRequest)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'desktop_pb2'
  # @@protoc_insertion_point(class_scope:PB_Desktop.Status)
  })
_sym_db.RegisterMessage(Status)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n#com.flipperdevices.protobuf.desktop'
  _ISLOCKEDREQUEST._serialized_start=29
  _ISLOCKEDREQUEST._serialized_end=46
  _UNLOCKREQUEST._serialized_start=48
  _UNLOCKREQUEST._serialized_end=63
  _STATUSSUBSCRIBEREQUEST._serialized_start=65
  _STATUSSUBSCRIBEREQUEST._serialized_end=89
  _STATUSUNSUBSCRIBEREQUEST._serialized_start=91
  _STATUSUNSUBSCRIBEREQUEST._serialized_end=117
  _STATUS._serialized_start=119
  _STATUS._serialized_end=143
# @@protoc_insertion_point(module_scope)
