# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gui.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tgui.proto\x12\x06PB_Gui\"K\n\x0bScreenFrame\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12.\n\x0borientation\x18\x02 \x01(\x0e\x32\x19.PB_Gui.ScreenOrientation\"\x1a\n\x18StartScreenStreamRequest\"\x19\n\x17StopScreenStreamRequest\"W\n\x15SendInputEventRequest\x12\x1d\n\x03key\x18\x01 \x01(\x0e\x32\x10.PB_Gui.InputKey\x12\x1f\n\x04type\x18\x02 \x01(\x0e\x32\x11.PB_Gui.InputType\"Z\n\x1aStartVirtualDisplayRequest\x12(\n\x0b\x66irst_frame\x18\x01 \x01(\x0b\x32\x13.PB_Gui.ScreenFrame\x12\x12\n\nsend_input\x18\x02 \x01(\x08\"\x1b\n\x19StopVirtualDisplayRequest*C\n\x08InputKey\x12\x06\n\x02UP\x10\x00\x12\x08\n\x04\x44OWN\x10\x01\x12\t\n\x05RIGHT\x10\x02\x12\x08\n\x04LEFT\x10\x03\x12\x06\n\x02OK\x10\x04\x12\x08\n\x04\x42\x41\x43K\x10\x05*D\n\tInputType\x12\t\n\x05PRESS\x10\x00\x12\x0b\n\x07RELEASE\x10\x01\x12\t\n\x05SHORT\x10\x02\x12\x08\n\x04LONG\x10\x03\x12\n\n\x06REPEAT\x10\x04*Y\n\x11ScreenOrientation\x12\x0e\n\nHORIZONTAL\x10\x00\x12\x13\n\x0fHORIZONTAL_FLIP\x10\x01\x12\x0c\n\x08VERTICAL\x10\x02\x12\x11\n\rVERTICAL_FLIP\x10\x03\x42$\n\"com.flipperdevices.protobuf.screenb\x06proto3')

_INPUTKEY = DESCRIPTOR.enum_types_by_name['InputKey']
InputKey = enum_type_wrapper.EnumTypeWrapper(_INPUTKEY)
_INPUTTYPE = DESCRIPTOR.enum_types_by_name['InputType']
InputType = enum_type_wrapper.EnumTypeWrapper(_INPUTTYPE)
_SCREENORIENTATION = DESCRIPTOR.enum_types_by_name['ScreenOrientation']
ScreenOrientation = enum_type_wrapper.EnumTypeWrapper(_SCREENORIENTATION)
UP = 0
DOWN = 1
RIGHT = 2
LEFT = 3
OK = 4
BACK = 5
PRESS = 0
RELEASE = 1
SHORT = 2
LONG = 3
REPEAT = 4
HORIZONTAL = 0
HORIZONTAL_FLIP = 1
VERTICAL = 2
VERTICAL_FLIP = 3


_SCREENFRAME = DESCRIPTOR.message_types_by_name['ScreenFrame']
_STARTSCREENSTREAMREQUEST = DESCRIPTOR.message_types_by_name['StartScreenStreamRequest']
_STOPSCREENSTREAMREQUEST = DESCRIPTOR.message_types_by_name['StopScreenStreamRequest']
_SENDINPUTEVENTREQUEST = DESCRIPTOR.message_types_by_name['SendInputEventRequest']
_STARTVIRTUALDISPLAYREQUEST = DESCRIPTOR.message_types_by_name['StartVirtualDisplayRequest']
_STOPVIRTUALDISPLAYREQUEST = DESCRIPTOR.message_types_by_name['StopVirtualDisplayRequest']
ScreenFrame = _reflection.GeneratedProtocolMessageType('ScreenFrame', (_message.Message,), {
  'DESCRIPTOR' : _SCREENFRAME,
  '__module__' : 'gui_pb2'
  # @@protoc_insertion_point(class_scope:PB_Gui.ScreenFrame)
  })
_sym_db.RegisterMessage(ScreenFrame)

StartScreenStreamRequest = _reflection.GeneratedProtocolMessageType('StartScreenStreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTSCREENSTREAMREQUEST,
  '__module__' : 'gui_pb2'
  # @@protoc_insertion_point(class_scope:PB_Gui.StartScreenStreamRequest)
  })
_sym_db.RegisterMessage(StartScreenStreamRequest)

StopScreenStreamRequest = _reflection.GeneratedProtocolMessageType('StopScreenStreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOPSCREENSTREAMREQUEST,
  '__module__' : 'gui_pb2'
  # @@protoc_insertion_point(class_scope:PB_Gui.StopScreenStreamRequest)
  })
_sym_db.RegisterMessage(StopScreenStreamRequest)

SendInputEventRequest = _reflection.GeneratedProtocolMessageType('SendInputEventRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDINPUTEVENTREQUEST,
  '__module__' : 'gui_pb2'
  # @@protoc_insertion_point(class_scope:PB_Gui.SendInputEventRequest)
  })
_sym_db.RegisterMessage(SendInputEventRequest)

StartVirtualDisplayRequest = _reflection.GeneratedProtocolMessageType('StartVirtualDisplayRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTVIRTUALDISPLAYREQUEST,
  '__module__' : 'gui_pb2'
  # @@protoc_insertion_point(class_scope:PB_Gui.StartVirtualDisplayRequest)
  })
_sym_db.RegisterMessage(StartVirtualDisplayRequest)

StopVirtualDisplayRequest = _reflection.GeneratedProtocolMessageType('StopVirtualDisplayRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOPVIRTUALDISPLAYREQUEST,
  '__module__' : 'gui_pb2'
  # @@protoc_insertion_point(class_scope:PB_Gui.StopVirtualDisplayRequest)
  })
_sym_db.RegisterMessage(StopVirtualDisplayRequest)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\"com.flipperdevices.protobuf.screen'
  _INPUTKEY._serialized_start=363
  _INPUTKEY._serialized_end=430
  _INPUTTYPE._serialized_start=432
  _INPUTTYPE._serialized_end=500
  _SCREENORIENTATION._serialized_start=502
  _SCREENORIENTATION._serialized_end=591
  _SCREENFRAME._serialized_start=21
  _SCREENFRAME._serialized_end=96
  _STARTSCREENSTREAMREQUEST._serialized_start=98
  _STARTSCREENSTREAMREQUEST._serialized_end=124
  _STOPSCREENSTREAMREQUEST._serialized_start=126
  _STOPSCREENSTREAMREQUEST._serialized_end=151
  _SENDINPUTEVENTREQUEST._serialized_start=153
  _SENDINPUTEVENTREQUEST._serialized_end=240
  _STARTVIRTUALDISPLAYREQUEST._serialized_start=242
  _STARTVIRTUALDISPLAYREQUEST._serialized_end=332
  _STOPVIRTUALDISPLAYREQUEST._serialized_start=334
  _STOPVIRTUALDISPLAYREQUEST._serialized_end=361
# @@protoc_insertion_point(module_scope)
