# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: property.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproperty.proto\x12\x0bPB_Property\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\")\n\x0bGetResponse\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\tB&\n$com.flipperdevices.protobuf.propertyb\x06proto3')



_GETREQUEST = DESCRIPTOR.message_types_by_name['GetRequest']
_GETRESPONSE = DESCRIPTOR.message_types_by_name['GetResponse']
GetRequest = _reflection.GeneratedProtocolMessageType('GetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETREQUEST,
  '__module__' : 'property_pb2'
  # @@protoc_insertion_point(class_scope:PB_Property.GetRequest)
  })
_sym_db.RegisterMessage(GetRequest)

GetResponse = _reflection.GeneratedProtocolMessageType('GetResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETRESPONSE,
  '__module__' : 'property_pb2'
  # @@protoc_insertion_point(class_scope:PB_Property.GetResponse)
  })
_sym_db.RegisterMessage(GetResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n$com.flipperdevices.protobuf.property'
  _GETREQUEST._serialized_start=31
  _GETREQUEST._serialized_end=56
  _GETRESPONSE._serialized_start=58
  _GETRESPONSE._serialized_end=99
# @@protoc_insertion_point(module_scope)
